using System.Text;
using RaspberryPiManager.Models;

namespace RaspberryPiManager.Utilities;

public interface IScriptGenerator
{
    string GenerateFirstBootScript(PiSettings settings);
    string GeneratePostInstallScript(CustomScripts scripts, PackageSettings packages);
    string GenerateUserSetupScript(UserSettings users);
    string GenerateNetworkSetupScript(NetworkSettings network);
    string GenerateSSHSetupScript(SSHSettings ssh);
}

public class ScriptGenerator : IScriptGenerator
{
    public string GenerateFirstBootScript(PiSettings settings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/bin/bash");
        sb.AppendLine("set -e");
        sb.AppendLine();
        sb.AppendLine("# Raspberry Pi First Boot Script");
        sb.AppendLine("# Generated by Raspberry Pi Manager");
        sb.AppendLine();

        // Network setup
        if (settings.Network.EnableWiFi)
        {
            sb.AppendLine("# Configure WiFi");
            sb.AppendLine("if [ -f /boot/wpa_supplicant.conf ]; then");
            sb.AppendLine("    cp /boot/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf");
            sb.AppendLine("fi");
            sb.AppendLine();
        }

        // SSH setup
        if (settings.SSH.EnableSSH)
        {
            sb.AppendLine("# Enable SSH");
            sb.AppendLine("systemctl enable ssh");
            sb.AppendLine("systemctl start ssh");
            sb.AppendLine();

            if (settings.SSH.AuthorizedKeys.Count > 0)
            {
                sb.AppendLine("# Add authorized SSH keys");
                sb.AppendLine("mkdir -p ~/.ssh");
                sb.AppendLine("chmod 700 ~/.ssh");
                foreach (var key in settings.SSH.AuthorizedKeys)
                {
                    sb.AppendLine($"echo \"{key}\" >> ~/.ssh/authorized_keys");
                }
                sb.AppendLine("chmod 600 ~/.ssh/authorized_keys");
                sb.AppendLine();
            }
        }

        // System settings
        if (!string.IsNullOrEmpty(settings.System.Hostname))
        {
            sb.AppendLine($"# Set hostname");
            sb.AppendLine($"hostnamectl set-hostname {settings.System.Hostname}");
            sb.AppendLine($"echo \"127.0.1.1 {settings.System.Hostname}\" >> /etc/hosts");
            sb.AppendLine();
        }

        if (!string.IsNullOrEmpty(settings.System.Locale))
        {
            sb.AppendLine($"# Set locale");
            sb.AppendLine($"locale-gen {settings.System.Locale}");
            sb.AppendLine($"update-locale LANG={settings.System.Locale}");
            sb.AppendLine();
        }

        if (!string.IsNullOrEmpty(settings.System.Timezone))
        {
            sb.AppendLine($"# Set timezone");
            sb.AppendLine($"timedatectl set-timezone {settings.System.Timezone}");
            sb.AppendLine();
        }

        // Package installation
        if (settings.Packages.PackagesToInstall.Count > 0)
        {
            sb.AppendLine("# Install packages");
            if (settings.Packages.UpdatePackageList)
            {
                sb.AppendLine("apt-get update -y");
            }
            sb.AppendLine($"apt-get install -y {string.Join(" ", settings.Packages.PackagesToInstall)}");
            sb.AppendLine();
        }

        // Custom scripts
        foreach (var script in settings.Scripts.PostInstallScripts)
        {
            sb.AppendLine("# Custom post-install script");
            sb.AppendLine(script);
            sb.AppendLine();
        }

        // Cleanup
        sb.AppendLine("# Cleanup");
        sb.AppendLine("rm /boot/firstrun.sh");
        sb.AppendLine("systemctl disable firstrun.service");
        sb.AppendLine();
        sb.AppendLine("echo 'First boot setup completed!'");

        return sb.ToString();
    }

    public string GeneratePostInstallScript(CustomScripts scripts, PackageSettings packages)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/bin/bash");
        sb.AppendLine("set -e");
        sb.AppendLine();

        if (packages.UpdatePackageList)
        {
            sb.AppendLine("apt-get update -y");
        }

        if (packages.PackagesToInstall.Count > 0)
        {
            sb.AppendLine($"apt-get install -y {string.Join(" ", packages.PackagesToInstall)}");
        }

        if (packages.UpgradePackages)
        {
            sb.AppendLine("apt-get upgrade -y");
        }

        foreach (var script in scripts.PostInstallScripts)
        {
            sb.AppendLine(script);
        }

        return sb.ToString();
    }

    public string GenerateUserSetupScript(UserSettings users)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/bin/bash");
        sb.AppendLine("set -e");
        sb.AppendLine();

        foreach (var user in users.Users)
        {
            sb.AppendLine($"# Create user: {user.Username}");
            sb.AppendLine($"useradd -m -s /bin/bash {user.Username}");

            if (user.HasSudo)
            {
                sb.AppendLine($"usermod -aG sudo {user.Username}");
            }

            foreach (var group in user.Groups)
            {
                sb.AppendLine($"usermod -aG {group} {user.Username}");
            }

            // Set password (would need to be encrypted in production)
            if (!string.IsNullOrEmpty(user.Password))
            {
                sb.AppendLine($"echo '{user.Username}:{user.Password}' | chpasswd");
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    public string GenerateNetworkSetupScript(NetworkSettings network)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/bin/bash");
        sb.AppendLine("set -e");
        sb.AppendLine();

        if (network.EnableWiFi)
        {
            sb.AppendLine("# Configure WiFi");
            sb.AppendLine("if [ -f /boot/wpa_supplicant.conf ]; then");
            sb.AppendLine("    cp /boot/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf");
            sb.AppendLine("    systemctl restart wpa_supplicant");
            sb.AppendLine("fi");
        }

        if (network.UseStaticIP && !string.IsNullOrEmpty(network.StaticIP))
        {
            sb.AppendLine("# Configure static IP");
            sb.AppendLine($"# Static IP: {network.StaticIP}");
            sb.AppendLine($"# Gateway: {network.Gateway}");
            sb.AppendLine($"# DNS: {network.DNS}");
        }

        return sb.ToString();
    }

    public string GenerateSSHSetupScript(SSHSettings ssh)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/bin/bash");
        sb.AppendLine("set -e");
        sb.AppendLine();

        if (ssh.EnableSSH)
        {
            sb.AppendLine("# Enable SSH");
            sb.AppendLine("systemctl enable ssh");
            sb.AppendLine("systemctl start ssh");
            sb.AppendLine();

            if (ssh.Port != 22)
            {
                sb.AppendLine($"# Change SSH port to {ssh.Port}");
                sb.AppendLine($"sed -i 's/#Port 22/Port {ssh.Port}/' /etc/ssh/sshd_config");
                sb.AppendLine("systemctl restart ssh");
            }

            if (!ssh.EnablePasswordAuth)
            {
                sb.AppendLine("# Disable password authentication");
                sb.AppendLine("sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config");
                sb.AppendLine("systemctl restart ssh");
            }

            if (ssh.AuthorizedKeys.Count > 0)
            {
                sb.AppendLine("# Add authorized keys");
                sb.AppendLine("mkdir -p ~/.ssh");
                sb.AppendLine("chmod 700 ~/.ssh");
                foreach (var key in ssh.AuthorizedKeys)
                {
                    sb.AppendLine($"echo \"{key}\" >> ~/.ssh/authorized_keys");
                }
                sb.AppendLine("chmod 600 ~/.ssh/authorized_keys");
            }
        }

        return sb.ToString();
    }
}
